PINECONE_API_KEY="pcsk_46T61Y_QPQhEC1tvgp7g4H8mMpkGvUB34fYZDrSag3YZCg8LTEiWrHFS8GXKqvt2vKGZkc"
PINECONE_ENVIRONMENT="us-east-1"
PINECONE_INDEX_NAME="nietzsche-rag"
GROQ_API_KEY="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"
EMAIL_SENDER="1starun8@gmail.com"
EMAIL_RECEIVER="1starun8@gmail.com"
EMAIL_APP_PASSWORD="yrnbjbaafmntensi"

